### ISSUE TITLE
Lack of info how to use that

### ISSUE THREAD

**Issue by ghost** [turgayozgur/magento2-c2c#1]
Hi @turgayozgur ,

I installed your module, however, I do not know how to use it at all.
I cannot see any differences in the admin panel or in the frontend.

Could you describe a little how to use this module?

**Comment by turgayozgur** [comment]
Hi tommy,

This extension can not adding a fully product but this can add a simple product and can be referance for more to you.

Write this to address bar for the extension index page (add product page):

 domain.com/C2C (for example: http://localhost/magento2/C2C)

You can see My Products link at customer left sidebar for listing customer's products.

Note: disable full page caching for drag and drop image upload. I could not find time for fixing this issue.

**Comment by ghost** [comment]
I typed to the address bar the url that you recommended, however the page was not found.
I see your module in `composer.json`:
`"turgayozgur/c2c": "2.0.0"`
I type in command line `composer install` and everything is already up-to-date.
What should I do in such a case? How can I check if the module was installed correctly?

**Comment by turgayozgur** [comment]
Go to your magento web site root directory and open terminal(cmd) here.

Type `php bin/magento setup:upgrade` and press enter. 

Clear magento cache. Thats all.

**Comment by ghost** [comment]
After taking this steps every url that I try to access is blank.

At the end of execution of `php bin/magento setup:upgrade` I noticed:
`Please re-run Magento compile command`

But I do not see any Magento compile command. What do you do then?

**Comment by turgayozgur** [comment]
I dont know anything about recompile but i found this: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-compiler.html
